server:
  port: 8086
  servlet:
    context-path: /api/v1

spring:
  application:
    name: ORDER-SERVICE
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/order_service_db
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ACC-Brijalan-Training/config-api.git
          clone-on-start: true
          default-label: main


#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    serviceUrl:
#      defaultZone: http://${EUREKA_SERVER_ADDRESS:localhost}:8761/eureka